version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Add Android SDK licenses
          command: mkdir -p $ANDROID_HOME/licenses/ && printf "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
      - run:
          name: Download Android build-tools 26.0.2
          command: echo y | sdkmanager "build-tools;26.0.2"
      - run:
          name: Download NDK
          command: echo y | sdkmanager "ndk-bundle"
      - run:
          name: Download submodules
          command: git submodule update --init --recursive
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - run:
          name: Build app
          command: ./gradlew assembleDebug --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
